fragment PageParts on Page {
  ... on PageSimple {
    title
    description
    teaser
    alias
    accessible
    body
  }
  ... on PageBlocks {
    title
    description
    teaser
    alias
    accessible
    blocks {
      __typename
      ... on PageBlocksBlocksHero {
        headline
        text
      }
      ... on PageBlocksBlocksFeatures {
        items {
          __typename
          title
          text
        }
      }
      ... on PageBlocksBlocksContent {
        body
      }
    }
  }
}

fragment NavMainParts on NavMain {
  ... on NavMainMainNav {
    menu {
      __typename
      title
      page {
        ... on Page {
          ... on PageSimple {
            title
            description
            teaser
            alias
            accessible
            body
          }
          ... on PageBlocks {
            title
            description
            teaser
            alias
            accessible
            blocks {
              __typename
              ... on PageBlocksBlocksHero {
                headline
                text
              }
              ... on PageBlocksBlocksFeatures {
                items {
                  __typename
                  title
                  text
                }
              }
              ... on PageBlocksBlocksContent {
                body
              }
            }
          }
        }
        ... on Document {
          id
        }
      }
      disabled
      showInMainNavigation
      children {
        __typename
        title
        page {
          ... on Page {
            ... on PageSimple {
              title
              description
              teaser
              alias
              accessible
              body
            }
            ... on PageBlocks {
              title
              description
              teaser
              alias
              accessible
              blocks {
                __typename
                ... on PageBlocksBlocksHero {
                  headline
                  text
                }
                ... on PageBlocksBlocksFeatures {
                  items {
                    __typename
                    title
                    text
                  }
                }
                ... on PageBlocksBlocksContent {
                  body
                }
              }
            }
          }
          ... on Document {
            id
          }
        }
        disabled
        showInMainNavigation
        children {
          __typename
          title
          page {
            ... on Page {
              ... on PageSimple {
                title
                description
                teaser
                alias
                accessible
                body
              }
              ... on PageBlocks {
                title
                description
                teaser
                alias
                accessible
                blocks {
                  __typename
                  ... on PageBlocksBlocksHero {
                    headline
                    text
                  }
                  ... on PageBlocksBlocksFeatures {
                    items {
                      __typename
                      title
                      text
                    }
                  }
                  ... on PageBlocksBlocksContent {
                    body
                  }
                }
              }
            }
            ... on Document {
              id
            }
          }
          description
          disabled
          showInMainNavigation
          children {
            __typename
            title
            page {
              ... on Page {
                ... on PageSimple {
                  title
                  description
                  teaser
                  alias
                  accessible
                  body
                }
                ... on PageBlocks {
                  title
                  description
                  teaser
                  alias
                  accessible
                  blocks {
                    __typename
                    ... on PageBlocksBlocksHero {
                      headline
                      text
                    }
                    ... on PageBlocksBlocksFeatures {
                      items {
                        __typename
                        title
                        text
                      }
                    }
                    ... on PageBlocksBlocksContent {
                      body
                    }
                  }
                }
              }
              ... on Document {
                id
              }
            }
            children {
              __typename
              title
              page {
                ... on Page {
                  ... on PageSimple {
                    title
                    description
                    teaser
                    alias
                    accessible
                    body
                  }
                  ... on PageBlocks {
                    title
                    description
                    teaser
                    alias
                    accessible
                    blocks {
                      __typename
                      ... on PageBlocksBlocksHero {
                        headline
                        text
                      }
                      ... on PageBlocksBlocksFeatures {
                        items {
                          __typename
                          title
                          text
                        }
                      }
                      ... on PageBlocksBlocksContent {
                        body
                      }
                    }
                  }
                }
                ... on Document {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}

fragment NavFooterParts on NavFooter {
  ... on NavFooterFooter {
    footerMenu {
      __typename
      title
      children {
        __typename
        title
        page {
          ... on Page {
            ... on PageSimple {
              title
              description
              teaser
              alias
              accessible
              body
            }
            ... on PageBlocks {
              title
              description
              teaser
              alias
              accessible
              blocks {
                __typename
                ... on PageBlocksBlocksHero {
                  headline
                  text
                }
                ... on PageBlocksBlocksFeatures {
                  items {
                    __typename
                    title
                    text
                  }
                }
                ... on PageBlocksBlocksContent {
                  body
                }
              }
            }
          }
          ... on Document {
            id
          }
        }
      }
    }
  }
}
