//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  page: Page;
  pageConnection: PageConnection;
  navMain: NavMain;
  navMainConnection: NavMainConnection;
  navFooter: NavFooter;
  navFooterConnection: NavFooterConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PageFilter>;
};


export type QueryNavMainArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryNavMainConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<NavMainFilter>;
};


export type QueryNavFooterArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryNavFooterConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<NavFooterFilter>;
};

export type DocumentFilter = {
  page?: InputMaybe<PageFilter>;
  navMain?: InputMaybe<NavMainFilter>;
  navFooter?: InputMaybe<NavFooterFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<DocumentFilter>;
};

export type DocumentNode = PageSimple | PageBlocks | NavMainMainNav | NavFooterFooter;

export type PageSimple = Node & Document & {
  __typename?: 'PageSimple';
  title: Scalars['String'];
  description?: Maybe<Scalars['String']>;
  teaser?: Maybe<Scalars['String']>;
  alias?: Maybe<Scalars['String']>;
  accessible?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['JSON']>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type PageBlocksBlocksHero = {
  __typename?: 'PageBlocksBlocksHero';
  headline?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['JSON']>;
};

export type PageBlocksBlocksFeaturesItems = {
  __typename?: 'PageBlocksBlocksFeaturesItems';
  title?: Maybe<Scalars['String']>;
  text?: Maybe<Scalars['String']>;
};

export type PageBlocksBlocksFeatures = {
  __typename?: 'PageBlocksBlocksFeatures';
  items?: Maybe<Array<Maybe<PageBlocksBlocksFeaturesItems>>>;
};

export type PageBlocksBlocksContent = {
  __typename?: 'PageBlocksBlocksContent';
  body?: Maybe<Scalars['JSON']>;
};

export type PageBlocksBlocks = PageBlocksBlocksHero | PageBlocksBlocksFeatures | PageBlocksBlocksContent;

export type PageBlocks = Node & Document & {
  __typename?: 'PageBlocks';
  title: Scalars['String'];
  description?: Maybe<Scalars['String']>;
  teaser?: Maybe<Scalars['String']>;
  alias?: Maybe<Scalars['String']>;
  accessible?: Maybe<Scalars['String']>;
  blocks?: Maybe<Array<Maybe<PageBlocksBlocks>>>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type Page = PageSimple | PageBlocks;

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']>>>;
};

export type PageSimpleBodyVideoPlayerVideosFilter = {
  url?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  poster?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
};

export type PageSimpleBodyVideoPlayerFilter = {
  videos?: InputMaybe<PageSimpleBodyVideoPlayerVideosFilter>;
};

export type PageSimpleBodyFilter = {
  VideoPlayer?: InputMaybe<PageSimpleBodyVideoPlayerFilter>;
};

export type PageSimpleFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  teaser?: InputMaybe<ImageFilter>;
  alias?: InputMaybe<StringFilter>;
  accessible?: InputMaybe<StringFilter>;
  body?: InputMaybe<PageSimpleBodyFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']>;
  eq?: InputMaybe<Scalars['String']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type PageBlocksBlocksHeroFilter = {
  headline?: InputMaybe<StringFilter>;
  text?: InputMaybe<RichTextFilter>;
};

export type PageBlocksBlocksFeaturesItemsFilter = {
  title?: InputMaybe<StringFilter>;
  text?: InputMaybe<StringFilter>;
};

export type PageBlocksBlocksFeaturesFilter = {
  items?: InputMaybe<PageBlocksBlocksFeaturesItemsFilter>;
};

export type PageBlocksBlocksContentFilter = {
  body?: InputMaybe<RichTextFilter>;
};

export type PageBlocksBlocksFilter = {
  hero?: InputMaybe<PageBlocksBlocksHeroFilter>;
  features?: InputMaybe<PageBlocksBlocksFeaturesFilter>;
  content?: InputMaybe<PageBlocksBlocksContentFilter>;
};

export type PageBlocksFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  teaser?: InputMaybe<ImageFilter>;
  alias?: InputMaybe<StringFilter>;
  accessible?: InputMaybe<StringFilter>;
  blocks?: InputMaybe<PageBlocksBlocksFilter>;
};

export type PageFilter = {
  simple?: InputMaybe<PageSimpleFilter>;
  blocks?: InputMaybe<PageBlocksFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type NavMainMainNavMenuPage = PageSimple | PageBlocks;

export type NavMainMainNavMenuChildrenPage = PageSimple | PageBlocks;

export type NavMainMainNavMenuChildrenChildrenPage = PageSimple | PageBlocks;

export type NavMainMainNavMenuChildrenChildrenChildrenPage = PageSimple | PageBlocks;

export type NavMainMainNavMenuChildrenChildrenChildrenChildrenPage = PageSimple | PageBlocks;

export type NavMainMainNavMenuChildrenChildrenChildrenChildren = {
  __typename?: 'NavMainMainNavMenuChildrenChildrenChildrenChildren';
  title: Scalars['String'];
  page?: Maybe<NavMainMainNavMenuChildrenChildrenChildrenChildrenPage>;
};

export type NavMainMainNavMenuChildrenChildrenChildren = {
  __typename?: 'NavMainMainNavMenuChildrenChildrenChildren';
  title: Scalars['String'];
  page?: Maybe<NavMainMainNavMenuChildrenChildrenChildrenPage>;
  children?: Maybe<Array<Maybe<NavMainMainNavMenuChildrenChildrenChildrenChildren>>>;
};

export type NavMainMainNavMenuChildrenChildren = {
  __typename?: 'NavMainMainNavMenuChildrenChildren';
  title: Scalars['String'];
  page?: Maybe<NavMainMainNavMenuChildrenChildrenPage>;
  description?: Maybe<Scalars['String']>;
  disabled?: Maybe<Scalars['Boolean']>;
  showInMainNavigation?: Maybe<Scalars['Boolean']>;
  children?: Maybe<Array<Maybe<NavMainMainNavMenuChildrenChildrenChildren>>>;
};

export type NavMainMainNavMenuChildren = {
  __typename?: 'NavMainMainNavMenuChildren';
  title: Scalars['String'];
  page?: Maybe<NavMainMainNavMenuChildrenPage>;
  disabled?: Maybe<Scalars['Boolean']>;
  showInMainNavigation?: Maybe<Scalars['Boolean']>;
  children?: Maybe<Array<Maybe<NavMainMainNavMenuChildrenChildren>>>;
};

export type NavMainMainNavMenu = {
  __typename?: 'NavMainMainNavMenu';
  title: Scalars['String'];
  page?: Maybe<NavMainMainNavMenuPage>;
  disabled?: Maybe<Scalars['Boolean']>;
  showInMainNavigation?: Maybe<Scalars['Boolean']>;
  children?: Maybe<Array<Maybe<NavMainMainNavMenuChildren>>>;
};

export type NavMainMainNav = Node & Document & {
  __typename?: 'NavMainMainNav';
  menu?: Maybe<Array<Maybe<NavMainMainNavMenu>>>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type NavMain = NavMainMainNav;

export type NavMainMainNavMenuPageFilter = {
  page?: InputMaybe<PageFilter>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']>;
  exists?: InputMaybe<Scalars['Boolean']>;
};

export type NavMainMainNavMenuChildrenPageFilter = {
  page?: InputMaybe<PageFilter>;
};

export type NavMainMainNavMenuChildrenChildrenPageFilter = {
  page?: InputMaybe<PageFilter>;
};

export type NavMainMainNavMenuChildrenChildrenChildrenPageFilter = {
  page?: InputMaybe<PageFilter>;
};

export type NavMainMainNavMenuChildrenChildrenChildrenChildrenPageFilter = {
  page?: InputMaybe<PageFilter>;
};

export type NavMainMainNavMenuChildrenChildrenChildrenChildrenFilter = {
  title?: InputMaybe<StringFilter>;
  page?: InputMaybe<NavMainMainNavMenuChildrenChildrenChildrenChildrenPageFilter>;
};

export type NavMainMainNavMenuChildrenChildrenChildrenFilter = {
  title?: InputMaybe<StringFilter>;
  page?: InputMaybe<NavMainMainNavMenuChildrenChildrenChildrenPageFilter>;
  children?: InputMaybe<NavMainMainNavMenuChildrenChildrenChildrenChildrenFilter>;
};

export type NavMainMainNavMenuChildrenChildrenFilter = {
  title?: InputMaybe<StringFilter>;
  page?: InputMaybe<NavMainMainNavMenuChildrenChildrenPageFilter>;
  description?: InputMaybe<StringFilter>;
  disabled?: InputMaybe<BooleanFilter>;
  showInMainNavigation?: InputMaybe<BooleanFilter>;
  children?: InputMaybe<NavMainMainNavMenuChildrenChildrenChildrenFilter>;
};

export type NavMainMainNavMenuChildrenFilter = {
  title?: InputMaybe<StringFilter>;
  page?: InputMaybe<NavMainMainNavMenuChildrenPageFilter>;
  disabled?: InputMaybe<BooleanFilter>;
  showInMainNavigation?: InputMaybe<BooleanFilter>;
  children?: InputMaybe<NavMainMainNavMenuChildrenChildrenFilter>;
};

export type NavMainMainNavMenuFilter = {
  title?: InputMaybe<StringFilter>;
  page?: InputMaybe<NavMainMainNavMenuPageFilter>;
  disabled?: InputMaybe<BooleanFilter>;
  showInMainNavigation?: InputMaybe<BooleanFilter>;
  children?: InputMaybe<NavMainMainNavMenuChildrenFilter>;
};

export type NavMainMainNavFilter = {
  menu?: InputMaybe<NavMainMainNavMenuFilter>;
};

export type NavMainFilter = {
  mainNav?: InputMaybe<NavMainMainNavFilter>;
};

export type NavMainConnectionEdges = {
  __typename?: 'NavMainConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<NavMain>;
};

export type NavMainConnection = Connection & {
  __typename?: 'NavMainConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<NavMainConnectionEdges>>>;
};

export type NavFooterFooterFooterMenuChildrenPage = PageSimple | PageBlocks;

export type NavFooterFooterFooterMenuChildren = {
  __typename?: 'NavFooterFooterFooterMenuChildren';
  title: Scalars['String'];
  page: NavFooterFooterFooterMenuChildrenPage;
};

export type NavFooterFooterFooterMenu = {
  __typename?: 'NavFooterFooterFooterMenu';
  title: Scalars['String'];
  children?: Maybe<Array<Maybe<NavFooterFooterFooterMenuChildren>>>;
};

export type NavFooterFooter = Node & Document & {
  __typename?: 'NavFooterFooter';
  footerMenu?: Maybe<Array<Maybe<NavFooterFooterFooterMenu>>>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type NavFooter = NavFooterFooter;

export type NavFooterFooterFooterMenuChildrenPageFilter = {
  page?: InputMaybe<PageFilter>;
};

export type NavFooterFooterFooterMenuChildrenFilter = {
  title?: InputMaybe<StringFilter>;
  page?: InputMaybe<NavFooterFooterFooterMenuChildrenPageFilter>;
};

export type NavFooterFooterFooterMenuFilter = {
  title?: InputMaybe<StringFilter>;
  children?: InputMaybe<NavFooterFooterFooterMenuChildrenFilter>;
};

export type NavFooterFooterFilter = {
  footerMenu?: InputMaybe<NavFooterFooterFooterMenuFilter>;
};

export type NavFooterFilter = {
  footer?: InputMaybe<NavFooterFooterFilter>;
};

export type NavFooterConnectionEdges = {
  __typename?: 'NavFooterConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<NavFooter>;
};

export type NavFooterConnection = Connection & {
  __typename?: 'NavFooterConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<NavFooterConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updatePage: Page;
  createPage: Page;
  updateNavMain: NavMain;
  createNavMain: NavMain;
  updateNavFooter: NavFooter;
  createNavFooter: NavFooter;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String'];
  params: PageMutation;
};


export type MutationUpdateNavMainArgs = {
  relativePath: Scalars['String'];
  params: NavMainMutation;
};


export type MutationCreateNavMainArgs = {
  relativePath: Scalars['String'];
  params: NavMainMutation;
};


export type MutationUpdateNavFooterArgs = {
  relativePath: Scalars['String'];
  params: NavFooterMutation;
};


export type MutationCreateNavFooterArgs = {
  relativePath: Scalars['String'];
  params: NavFooterMutation;
};

export type DocumentUpdateMutation = {
  page?: InputMaybe<PageMutation>;
  navMain?: InputMaybe<NavMainMutation>;
  navFooter?: InputMaybe<NavFooterMutation>;
  relativePath?: InputMaybe<Scalars['String']>;
};

export type DocumentMutation = {
  page?: InputMaybe<PageMutation>;
  navMain?: InputMaybe<NavMainMutation>;
  navFooter?: InputMaybe<NavFooterMutation>;
};

export type PageSimpleMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  teaser?: InputMaybe<Scalars['String']>;
  alias?: InputMaybe<Scalars['String']>;
  accessible?: InputMaybe<Scalars['String']>;
  body?: InputMaybe<Scalars['JSON']>;
};

export type PageBlocksBlocksHeroMutation = {
  headline?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['JSON']>;
};

export type PageBlocksBlocksFeaturesItemsMutation = {
  title?: InputMaybe<Scalars['String']>;
  text?: InputMaybe<Scalars['String']>;
};

export type PageBlocksBlocksFeaturesMutation = {
  items?: InputMaybe<Array<InputMaybe<PageBlocksBlocksFeaturesItemsMutation>>>;
};

export type PageBlocksBlocksContentMutation = {
  body?: InputMaybe<Scalars['JSON']>;
};

export type PageBlocksBlocksMutation = {
  hero?: InputMaybe<PageBlocksBlocksHeroMutation>;
  features?: InputMaybe<PageBlocksBlocksFeaturesMutation>;
  content?: InputMaybe<PageBlocksBlocksContentMutation>;
};

export type PageBlocksMutation = {
  title?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  teaser?: InputMaybe<Scalars['String']>;
  alias?: InputMaybe<Scalars['String']>;
  accessible?: InputMaybe<Scalars['String']>;
  blocks?: InputMaybe<Array<InputMaybe<PageBlocksBlocksMutation>>>;
};

export type PageMutation = {
  simple?: InputMaybe<PageSimpleMutation>;
  blocks?: InputMaybe<PageBlocksMutation>;
};

export type NavMainMainNavMenuChildrenChildrenChildrenChildrenMutation = {
  title?: InputMaybe<Scalars['String']>;
  page?: InputMaybe<Scalars['String']>;
};

export type NavMainMainNavMenuChildrenChildrenChildrenMutation = {
  title?: InputMaybe<Scalars['String']>;
  page?: InputMaybe<Scalars['String']>;
  children?: InputMaybe<Array<InputMaybe<NavMainMainNavMenuChildrenChildrenChildrenChildrenMutation>>>;
};

export type NavMainMainNavMenuChildrenChildrenMutation = {
  title?: InputMaybe<Scalars['String']>;
  page?: InputMaybe<Scalars['String']>;
  description?: InputMaybe<Scalars['String']>;
  disabled?: InputMaybe<Scalars['Boolean']>;
  showInMainNavigation?: InputMaybe<Scalars['Boolean']>;
  children?: InputMaybe<Array<InputMaybe<NavMainMainNavMenuChildrenChildrenChildrenMutation>>>;
};

export type NavMainMainNavMenuChildrenMutation = {
  title?: InputMaybe<Scalars['String']>;
  page?: InputMaybe<Scalars['String']>;
  disabled?: InputMaybe<Scalars['Boolean']>;
  showInMainNavigation?: InputMaybe<Scalars['Boolean']>;
  children?: InputMaybe<Array<InputMaybe<NavMainMainNavMenuChildrenChildrenMutation>>>;
};

export type NavMainMainNavMenuMutation = {
  title?: InputMaybe<Scalars['String']>;
  page?: InputMaybe<Scalars['String']>;
  disabled?: InputMaybe<Scalars['Boolean']>;
  showInMainNavigation?: InputMaybe<Scalars['Boolean']>;
  children?: InputMaybe<Array<InputMaybe<NavMainMainNavMenuChildrenMutation>>>;
};

export type NavMainMainNavMutation = {
  menu?: InputMaybe<Array<InputMaybe<NavMainMainNavMenuMutation>>>;
};

export type NavMainMutation = {
  mainNav?: InputMaybe<NavMainMainNavMutation>;
};

export type NavFooterFooterFooterMenuChildrenMutation = {
  title?: InputMaybe<Scalars['String']>;
  page?: InputMaybe<Scalars['String']>;
};

export type NavFooterFooterFooterMenuMutation = {
  title?: InputMaybe<Scalars['String']>;
  children?: InputMaybe<Array<InputMaybe<NavFooterFooterFooterMenuChildrenMutation>>>;
};

export type NavFooterFooterMutation = {
  footerMenu?: InputMaybe<Array<InputMaybe<NavFooterFooterFooterMenuMutation>>>;
};

export type NavFooterMutation = {
  footer?: InputMaybe<NavFooterFooterMutation>;
};

export type NavQueryVariables = Exact<{ [key: string]: never; }>;


export type NavQuery = { __typename?: 'Query', navFooterConnection: { __typename?: 'NavFooterConnection', edges?: Array<{ __typename?: 'NavFooterConnectionEdges', node?: { __typename?: 'NavFooterFooter', _values: any } | null } | null> | null }, navMainConnection: { __typename?: 'NavMainConnection', edges?: Array<{ __typename?: 'NavMainConnectionEdges', node?: { __typename?: 'NavMainMainNav', _values: any } | null } | null> | null } };

type PageParts_PageSimple_Fragment = { __typename?: 'PageSimple', title: string, description?: string | null, teaser?: string | null, alias?: string | null, accessible?: string | null, body?: any | null };

type PageParts_PageBlocks_Fragment = { __typename?: 'PageBlocks', title: string, description?: string | null, teaser?: string | null, alias?: string | null, accessible?: string | null, blocks?: Array<{ __typename: 'PageBlocksBlocksHero', headline?: string | null, text?: any | null } | { __typename: 'PageBlocksBlocksFeatures', items?: Array<{ __typename: 'PageBlocksBlocksFeaturesItems', title?: string | null, text?: string | null } | null> | null } | { __typename: 'PageBlocksBlocksContent', body?: any | null } | null> | null };

export type PagePartsFragment = PageParts_PageSimple_Fragment | PageParts_PageBlocks_Fragment;

export type NavMainPartsFragment = { __typename?: 'NavMainMainNav', menu?: Array<{ __typename: 'NavMainMainNavMenu', title: string, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildren', title: string, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildren', title: string, description?: string | null, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildrenChildren', title: string, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildrenChildrenChildren', title: string, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null } | null> | null } | null> | null } | null> | null } | null> | null } | null> | null };

export type NavFooterPartsFragment = { __typename?: 'NavFooterFooter', footerMenu?: Array<{ __typename: 'NavFooterFooterFooterMenu', title: string, children?: Array<{ __typename: 'NavFooterFooterFooterMenuChildren', title: string, page: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } } | null> | null } | null> | null };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename?: 'PageSimple', id: string, title: string, description?: string | null, teaser?: string | null, alias?: string | null, accessible?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | { __typename?: 'PageBlocks', id: string, title: string, description?: string | null, teaser?: string | null, alias?: string | null, accessible?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksBlocksHero', headline?: string | null, text?: any | null } | { __typename: 'PageBlocksBlocksFeatures', items?: Array<{ __typename: 'PageBlocksBlocksFeaturesItems', title?: string | null, text?: string | null } | null> | null } | { __typename: 'PageBlocksBlocksContent', body?: any | null } | null> | null } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename?: 'PageSimple', id: string, title: string, description?: string | null, teaser?: string | null, alias?: string | null, accessible?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | { __typename?: 'PageBlocks', id: string, title: string, description?: string | null, teaser?: string | null, alias?: string | null, accessible?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksBlocksHero', headline?: string | null, text?: any | null } | { __typename: 'PageBlocksBlocksFeatures', items?: Array<{ __typename: 'PageBlocksBlocksFeaturesItems', title?: string | null, text?: string | null } | null> | null } | { __typename: 'PageBlocksBlocksContent', body?: any | null } | null> | null } | null } | null> | null } };

export type NavMainQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type NavMainQuery = { __typename?: 'Query', navMain: { __typename?: 'NavMainMainNav', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, menu?: Array<{ __typename: 'NavMainMainNavMenu', title: string, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildren', title: string, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildren', title: string, description?: string | null, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildrenChildren', title: string, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildrenChildrenChildren', title: string, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null } | null> | null } | null> | null } | null> | null } | null> | null } | null> | null } };

export type NavMainConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<NavMainFilter>;
}>;


export type NavMainConnectionQuery = { __typename?: 'Query', navMainConnection: { __typename?: 'NavMainConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavMainConnectionEdges', cursor: string, node?: { __typename?: 'NavMainMainNav', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, menu?: Array<{ __typename: 'NavMainMainNavMenu', title: string, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildren', title: string, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildren', title: string, description?: string | null, disabled?: boolean | null, showInMainNavigation?: boolean | null, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildrenChildren', title: string, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null, children?: Array<{ __typename: 'NavMainMainNavMenuChildrenChildrenChildrenChildren', title: string, page?: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } | null } | null> | null } | null> | null } | null> | null } | null> | null } | null> | null } | null } | null> | null } };

export type NavFooterQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type NavFooterQuery = { __typename?: 'Query', navFooter: { __typename?: 'NavFooterFooter', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, footerMenu?: Array<{ __typename: 'NavFooterFooterFooterMenu', title: string, children?: Array<{ __typename: 'NavFooterFooterFooterMenuChildren', title: string, page: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } } | null> | null } | null> | null } };

export type NavFooterConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
  filter?: InputMaybe<NavFooterFilter>;
}>;


export type NavFooterConnectionQuery = { __typename?: 'Query', navFooterConnection: { __typename?: 'NavFooterConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NavFooterConnectionEdges', cursor: string, node?: { __typename?: 'NavFooterFooter', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, footerMenu?: Array<{ __typename: 'NavFooterFooterFooterMenu', title: string, children?: Array<{ __typename: 'NavFooterFooterFooterMenuChildren', title: string, page: { __typename?: 'PageSimple', id: string } | { __typename?: 'PageBlocks', id: string } } | null> | null } | null> | null } | null } | null> | null } };

export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  ... on PageSimple {
    title
    description
    teaser
    alias
    accessible
    body
  }
  ... on PageBlocks {
    title
    description
    teaser
    alias
    accessible
    blocks {
      __typename
      ... on PageBlocksBlocksHero {
        headline
        text
      }
      ... on PageBlocksBlocksFeatures {
        items {
          __typename
          title
          text
        }
      }
      ... on PageBlocksBlocksContent {
        body
      }
    }
  }
}
    `;
export const NavMainPartsFragmentDoc = gql`
    fragment NavMainParts on NavMain {
  ... on NavMainMainNav {
    menu {
      __typename
      title
      page {
        ... on Page {
          ... on PageSimple {
            title
            description
            teaser
            alias
            accessible
            body
          }
          ... on PageBlocks {
            title
            description
            teaser
            alias
            accessible
            blocks {
              __typename
              ... on PageBlocksBlocksHero {
                headline
                text
              }
              ... on PageBlocksBlocksFeatures {
                items {
                  __typename
                  title
                  text
                }
              }
              ... on PageBlocksBlocksContent {
                body
              }
            }
          }
        }
        ... on Document {
          id
        }
      }
      disabled
      showInMainNavigation
      children {
        __typename
        title
        page {
          ... on Page {
            ... on PageSimple {
              title
              description
              teaser
              alias
              accessible
              body
            }
            ... on PageBlocks {
              title
              description
              teaser
              alias
              accessible
              blocks {
                __typename
                ... on PageBlocksBlocksHero {
                  headline
                  text
                }
                ... on PageBlocksBlocksFeatures {
                  items {
                    __typename
                    title
                    text
                  }
                }
                ... on PageBlocksBlocksContent {
                  body
                }
              }
            }
          }
          ... on Document {
            id
          }
        }
        disabled
        showInMainNavigation
        children {
          __typename
          title
          page {
            ... on Page {
              ... on PageSimple {
                title
                description
                teaser
                alias
                accessible
                body
              }
              ... on PageBlocks {
                title
                description
                teaser
                alias
                accessible
                blocks {
                  __typename
                  ... on PageBlocksBlocksHero {
                    headline
                    text
                  }
                  ... on PageBlocksBlocksFeatures {
                    items {
                      __typename
                      title
                      text
                    }
                  }
                  ... on PageBlocksBlocksContent {
                    body
                  }
                }
              }
            }
            ... on Document {
              id
            }
          }
          description
          disabled
          showInMainNavigation
          children {
            __typename
            title
            page {
              ... on Page {
                ... on PageSimple {
                  title
                  description
                  teaser
                  alias
                  accessible
                  body
                }
                ... on PageBlocks {
                  title
                  description
                  teaser
                  alias
                  accessible
                  blocks {
                    __typename
                    ... on PageBlocksBlocksHero {
                      headline
                      text
                    }
                    ... on PageBlocksBlocksFeatures {
                      items {
                        __typename
                        title
                        text
                      }
                    }
                    ... on PageBlocksBlocksContent {
                      body
                    }
                  }
                }
              }
              ... on Document {
                id
              }
            }
            children {
              __typename
              title
              page {
                ... on Page {
                  ... on PageSimple {
                    title
                    description
                    teaser
                    alias
                    accessible
                    body
                  }
                  ... on PageBlocks {
                    title
                    description
                    teaser
                    alias
                    accessible
                    blocks {
                      __typename
                      ... on PageBlocksBlocksHero {
                        headline
                        text
                      }
                      ... on PageBlocksBlocksFeatures {
                        items {
                          __typename
                          title
                          text
                        }
                      }
                      ... on PageBlocksBlocksContent {
                        body
                      }
                    }
                  }
                }
                ... on Document {
                  id
                }
              }
            }
          }
        }
      }
    }
  }
}
    `;
export const NavFooterPartsFragmentDoc = gql`
    fragment NavFooterParts on NavFooter {
  ... on NavFooterFooter {
    footerMenu {
      __typename
      title
      children {
        __typename
        title
        page {
          ... on Page {
            ... on PageSimple {
              title
              description
              teaser
              alias
              accessible
              body
            }
            ... on PageBlocks {
              title
              description
              teaser
              alias
              accessible
              blocks {
                __typename
                ... on PageBlocksBlocksHero {
                  headline
                  text
                }
                ... on PageBlocksBlocksFeatures {
                  items {
                    __typename
                    title
                    text
                  }
                }
                ... on PageBlocksBlocksContent {
                  body
                }
              }
            }
          }
          ... on Document {
            id
          }
        }
      }
    }
  }
}
    `;
export const NavDocument = gql`
    query nav {
  navFooterConnection {
    edges {
      node {
        ... on Document {
          _values
        }
      }
    }
  }
  navMainConnection {
    edges {
      node {
        ... on Document {
          _values
        }
      }
    }
  }
}
    `;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const NavMainDocument = gql`
    query navMain($relativePath: String!) {
  navMain(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavMainParts
  }
}
    ${NavMainPartsFragmentDoc}`;
export const NavMainConnectionDocument = gql`
    query navMainConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavMainFilter) {
  navMainConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavMainParts
      }
    }
  }
}
    ${NavMainPartsFragmentDoc}`;
export const NavFooterDocument = gql`
    query navFooter($relativePath: String!) {
  navFooter(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NavFooterParts
  }
}
    ${NavFooterPartsFragmentDoc}`;
export const NavFooterConnectionDocument = gql`
    query navFooterConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NavFooterFilter) {
  navFooterConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NavFooterParts
      }
    }
  }
}
    ${NavFooterPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      nav(variables?: NavQueryVariables, options?: C): Promise<{data: NavQuery, variables: NavQueryVariables, query: string}> {
        return requester<{data: NavQuery, variables: NavQueryVariables, query: string}, NavQueryVariables>(NavDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    navMain(variables: NavMainQueryVariables, options?: C): Promise<{data: NavMainQuery, variables: NavMainQueryVariables, query: string}> {
        return requester<{data: NavMainQuery, variables: NavMainQueryVariables, query: string}, NavMainQueryVariables>(NavMainDocument, variables, options);
      },
    navMainConnection(variables?: NavMainConnectionQueryVariables, options?: C): Promise<{data: NavMainConnectionQuery, variables: NavMainConnectionQueryVariables, query: string}> {
        return requester<{data: NavMainConnectionQuery, variables: NavMainConnectionQueryVariables, query: string}, NavMainConnectionQueryVariables>(NavMainConnectionDocument, variables, options);
      },
    navFooter(variables: NavFooterQueryVariables, options?: C): Promise<{data: NavFooterQuery, variables: NavFooterQueryVariables, query: string}> {
        return requester<{data: NavFooterQuery, variables: NavFooterQueryVariables, query: string}, NavFooterQueryVariables>(NavFooterDocument, variables, options);
      },
    navFooterConnection(variables?: NavFooterConnectionQueryVariables, options?: C): Promise<{data: NavFooterConnectionQuery, variables: NavFooterConnectionQueryVariables, query: string}> {
        return requester<{data: NavFooterConnectionQuery, variables: NavFooterConnectionQueryVariables, query: string}, NavFooterConnectionQueryVariables>(NavFooterConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    const data = await client.request({
      query: doc,
      variables: vars,
    });

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "http://localhost:4001/graphql", queries }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

  