query nav {
  navFooterConnection {
    edges {
      node {
        ... on Document {
          _values
        }
      }
    }
  }
  navMainConnection {
    edges {
      node {
        ... on Document {
          _values
        }
      }
    }
  }
}
